=== opentestingapi/impl_java/src/main/resources/templates/OpenTestApiSchema_v1.0.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "OpenTestApi Json Schema Version 1.0",
    "type": "object",
    "properties": {
        "testapi": {
            "type": "string",
            "description": "Specifies the TestAPI version."
        },
        "id": {
            "type": "string",
            "description": "Identifier of the test case."
        },
        "description": {
            "type": "string",
            "description": "The informal description of the test case."
        },
        "injections": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "injectid": {
                        "type": "string"
                    },
                    "service": {},
                    "checks": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "cron": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "timetolive": {
                        "type": "string",
                        "pattern": "^\\d+(s|m|h|d){0,1}$"
                    },
                    "sourcefile": {
                        "type": "string"
                    },
                    "replacements": {},
                    "active": {
                        "type": "boolean"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "injectid",
                    "service",
                    "checks",
                    "sourcefile"
                ]
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "checks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "checkid": {
                        "type": "string"
                    },
                    "service": {},
                    "validations": {},
                    "maxwaittime": {
                        "type": "string",
                        "pattern": "^\\d+(s|m|h|d){0,1}$"
                    },
                    "active": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "checkid",
                    "service",
                    "validations"
                ]
            },            
            "uniqueItems": true
        },
        "active": {
            "type": "boolean"
        },
        "labels": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "additionalProperties": false
    },
    "required": [
        "testapi",
        "id",
        "description"
    ]
}

=== opentestingapi/impl_java/src/test/resources/opentesting/systemtests/kafka_002/test.json
{
    "id" : "kafka_002",
    "testapi": "1.0",
    "active" : true,
    "description" : "kafka test case with acks",
    "labels" : ["stage-local", "department-mydepartment", "function-myfunction"],    
    "injections" : [
     {     
        "injectid": "inject-kafka-1",
        "cron" : [],
        "active" : true,
        "service" : {
            "type": "kafka",
            "connectstring": "host.testcontainers.internal:9092",
            "username": "",
            "password": "",
            "custom": [
               {
                  "key": "topic",
                  "value": "mytopic1"
               },
               {
                  "key": "header",
                  "value": "source_kafka_headers_1.json"
               },
               {
                  "key": "senddelay",
                  "value": "15000"
               },
               {
                  "key": "acks",
                  "value": "1"
               }
            ]
         },        
        "sourcefile" : "source_kafka_1.txt",        
        "timetolive": "1m",
        "checks" : [ "check-kafka-1" ],
        "replacements" : [
         {
            "key": "#replaceme1#",
            "value": [
               {
                  "order": 1,
                  "type": "list",
                  "value": "rep11|rep12|rep13"
               }
            ]
          },
          {
             "key": "#replaceme2#",
             "value": [
                {
                   "order": 1,
                   "type": "list",
                   "value": "rep21|rep22|rep23|rep24"
                },
                {
                   "order": 2,
                   "type": "now",
                   "value": "Q"
                }
             ],
             "maxlength": 10
           },
           {
             "key": "#replaceme3#",
             "value": [
                {
                   "order": 1,
                   "type": "regex",
                   "value": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                }
             ]
           }  
       ]
     }
    ],
    "checks": [
    {   
        "checkid" : "check-kafka-1",  
        "active" : true,
        "service" : {
            "type": "kafka",
            "connectstring": "host.testcontainers.internal:9092",
            "username": "",
            "password": "",
            "custom": [
               {
                  "key": "topic",
                  "value": "mytopic1"
               },
               {
                  "key": "group.id",
                  "value": "kafka_002.check-kafka-1.group"
               }
            ]
         },
         "validations": [
            {
               "order": 1,
               "request": "",
               "response": [ "check_kafka_1.txt" ],
               "type": "contains"
            }
         ],        
        "maxwaittime" : "30s",
        "mandatory" : true
     }
    ]
  }

=== opentestingapi/impl_java/scripts/environment_templating/test.json
{
   "id" : "test_#STAGE#",
   "testapi": "1.0",
   "active" : true,
   "description" : "oracle test case",
   "labels" : ["stage-#STAGE#", "department-mydepartment", "function-myfunction"],    
   "injections" : [
    {
       "injectid": "inject-oracle-1",
       "cron" : [],
       "active" : true,
       "service" : {
           "type": "oracle",
           "connectstring": "jdbc:oracle:thin:@#ORACLE_SERVER#:#ORACLE_PORT#/XE",
           "username": "e2etest",
           "password": "e2etest"
       },       
       "sourcefile" : "source_oracle_1.sql",
       "timetolive": "1m",
       "checks" : [ "check-oracle-1" ],
       "replacements" : [
        {
           "key": "#replaceme1#",
           "value": [
              {
                 "order": 1,
                 "type": "list",
                 "value": "rep11|rep12|rep13"
              }
           ]
         },
         {
            "key": "#replaceme2#",
            "value": [
               {
                  "order": 1,
                  "type": "list",
                  "value": "rep21|rep22|rep23|rep24"
               },
               {
                  "order": 2,
                  "type": "now",
                  "value": "Q"
               }
            ],
            "maxlength": 10
          },
          {
            "key": "#replaceme3#",
            "value": [
               {
                  "order": 3,
                  "type": "regex",
                  "value": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
               }
            ]
          }  
      ]
     }
   ],
   "checks": [
    {   
       "checkid" : "check-oracle-1",  
       "active" : true,
       "service" : {
           "type": "jdbc",
           "connectstring": "jdbc:oracle:thin:@#ORACLE_SERVER#:#ORACLE_PORT#/XE",
           "username": "e2etest",
           "password": "e2etest"
        },
        "validations": [
        {
           "order": 1,
           "request": "check_oracle_param_1.sql",
           "response": [ "check_oracle_1.json" ],
           "type": "equals"
        }],
       "maxwaittime" : "10s",
       "mandatory" : true
    }
   ]
 }

=== opentestingapi/impl_java/src/test/resources/opentesting/systemtests/s3_001/test.json
{
    "id" : "s3_001",
    "testapi": "1.0",
    "active" : true,
    "description" : "s3 test case",
    "labels" : ["stage-local", "department-mydepartment", "function-myfunction"],    
    "injections" : [
     {
         "injectid": "inject-s3-1",
         "cron" : [],
         "active" : true,
         "service" : {
            "type": "s3",
            "connectstring": "host.testcontainers.internal:29000",
            "username": "minio-root-user",
            "password": "minio-root-password",
            "custom": [
             {
                "key": "region",
                "value": "eu-central-1"
             },
             {
                "key": "bucketName",
                "value": "mybucket-#RANDOMVALUE#"
             },
             {
                "key": "fileName",
                "value": "myfile-#RANDOMVALUE#.json"
             }
            ]
        },           
         "sourcefile" : "s3_file.json",
         "timetolive": "1m",
         "checks" : [ "check-s3-1" ],
         "replacements" : [
          {
            "key": "#RANDOMVALUE#",
            "value": [
              {
                "order": 1,
                "type": "list",
                "value": "a|b|c"
              }
            ]
          }
        ]
      }
    ],
    "checks": [
     {   
        "checkid" : "check-s3-1",  
        "active" : true,
        "service" : {
          "type": "s3",
          "connectstring": "host.testcontainers.internal:29000",
          "username": "minio-root-user",
          "password": "minio-root-password",
          "custom": [
            {
              "key": "region",
              "value": "eu-central-1"
           },
           {
              "key": "bucketName",
              "value": "mybucket-#RANDOMVALUE#"
           },
           {
              "key": "fileName",
              "value": "myfile-#RANDOMVALUE#.json"
           }
          ]
        },
        "validations": [
          {
              "order": 1,
              "request": "",
              "response": [ "s3_file.json" ],
              "type": "equals"
          }
        ],          
        "maxwaittime" : "10s",
        "mandatory" : true,
        "injects" : [ ],
        "checks" : [ ],
        "result2random" : [ "test2" ]
     }
    ]
  }

=== opentestingapi/impl_java/src/test/resources/opentesting/systemtests/jsonschema_001/test.json
{
    "id" : "jsonschema_001",
    "testapi": "1.1",
    "active" : true,
    "description" : "jsonschema test case",
    "labels" : ["stage-local", "department-mydepartment", "function-myfunction"],    
    "injections" : [
      {
          "injectid": "inject-rest-1",
          "cron" : [],
          "active" : true,
          "service" : {
             "type": "rest",
             "connectstring": "http://host.testcontainers.internal:50000/dummy/post",
             "username": "",
             "password": "",
             "custom": [
               {
                 "key": "type",
                 "value": "POST"
               },
               {
                 "key": "header",
                 "value": "source_rest_headers_1.json"
               }
             ]
         },           
          "sourcefile" : "source_rest_1.json",
          "timetolive": "1m",
          "checks" : [ "check-rest-1" ]
       }
     ],
     "checks": [
      {   
         "checkid" : "check-rest-1",  
         "active" : true,
         "service" : {
           "type": "rest",
           "connectstring": "http://host.testcontainers.internal:50000/dummy/get",
           "username": "",
           "password": "",
           "custom": [
             {
               "key": "type",
               "value": "GET"
             },
             {
               "key": "header",
               "value": "check_rest_headers_1.json"
             }
           ]
         },
         "validations": [
           {
               "order": 1,
               "request": "",
               "__comment": "check structure of the response",
               "response": [ "check_rest_1.json" ],
               "type": "jsonschema"
           },
           {
               "order": 2,
               "request": "",
               "__comment": "check content of the response",
               "response": [ "check_rest_2.json" ],
               "type": "regex"
           }
         ],          
         "maxwaittime" : "10s",
         "mandatory" : true
      }
     ]
   }

=== opentestingapi/impl_java/src/test/resources/opentesting/systemtests/cassandra_001/test.json
{
    "id" : "cassandra_001",
    "testapi": "1.0",
    "active" : true,
    "description" : "cassandra test case",
    "labels" : ["stage-local", "department-mydepartment", "function-myfunction"],    
    "injections" : [
     {
        "injectid": "inject-cassandra-1",        
        "cron" : [],
        "active" : true,
        "service" : {
            "type": "cassandra",
            "connectstring": "host.testcontainers.internal:9042",
            "username": "e2etest",
            "password": "e2etest",
            "custom": [
               {
                  "key": "datacenter",
                  "value": "datacenter1"
               }
            ]
         },      
        "sourcefile" : "source_cassandra_1.cql",
        "timetolive": "1m",
        "checks" : [ "check-cassandra-1", "check-to-fail-cassandra-2" ],
        "replacements" : [
         {
            "key": "#replaceme1#",
            "value": [
               {
                  "order": 1,
                  "type": "list",
                  "value": "rep11|rep12|rep13"
               }
            ]
          },
          {
             "key": "#replaceme2#",
             "value": [
                {
                   "order": 1,
                   "type": "list",
                   "value": "rep21|rep22|rep23|rep24"
                },
                {
                   "order": 2,
                   "type": "now",
                   "value": "Q"
                }
             ],
             "maxlength": 10
           },
           {
             "key": "#replaceme3#",
             "value": [
                {
                   "order": 3,
                   "type": "regex",
                   "value": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
                }
             ]
           }  
       ]
     }
    ],
    "checks": [
     {     
        "checkid" : "check-cassandra-1",
        "active" : true,
        "service" : {
            "type": "cassandra",
            "connectstring": "host.testcontainers.internal:9042",
            "username": "e2etest",
            "password": "e2etest",
            "custom": [
               {
                  "key": "datacenter",
                  "value": "datacenter1"
               }
            ]
         },
         "validations": [
            {
               "order": 1,
               "request": "check_cassandra_param_1.cql",
               "response": [ "check_cassandra_1.json" ],
               "type": "equals"
            }
         ],
        "maxwaittime" : "10s",
        "intervall" : "5s",
        "mandatory" : true
     }, {   
        "checkid" : "check-to-fail-cassandra-2",  
        "active" : true,
        "service" : {
            "type": "cassandra",
            "connectstring": "host.testcontainers.internal:9042",
            "username": "e2etest",
            "password": "e2etest",
            "custom": [
               {
                  "key": "datacenter",
                  "value": "datacenter1"
               }
            ]
         },
         "validations": [
            {
               "order": 1,
               "request": "check_cassandra_param_2.cql",
               "response": [ "check_cassandra_2.json" ],
               "type": "equals"
            }
         ],
        "maxwaittime" : "10s",
        "intervall" : "5s",
        "mandatory" : false
     }
    ]
  }
